FROM wyattmunson/cicd-base:0.1.1

RUN apk add --no-cache aws-cli

# RUN curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
# RUN unzip awscliv2.zip
# RUN ./aws/install

# # Remove unnecessary files
# RUN rm awscliv2.zip
# RUN rm -rf /aws